# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: rapids-cli
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: ${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install -v .

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - importlib-metadata >=4.13.0
    - cuda-pathfinder >=1.2.3
    - nvidia-ml-py >=12.0
    - packaging
    - psutil
    - pyyaml
    - rich
    - rich-click

tests:
  - script:
      - rapids --help
      - rapids doctor --help

about:
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
