# Copyright (c) 2025, NVIDIA CORPORATION.
{% set pyproject = load_file_data("../../../pyproject.toml", from_recipe_dir=True)  %}
{% set proj = pyproject.get('project') %}
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: rapids-cli
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install -v .
  python:
    entry_points:
    {% for module, entrypoints in project.get('entry-points').items() %}
    {% for name, path in entrypoints.items() %}
      - {{ name }} = {{ module }}.{{ path }}
    {% endfor %}
    {% endfor %}

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.0
  run:
    - python
    - importlib-metadata >=4.13.0
    - nvidia-ml-py >=12.0
    - packaging
    - psutil
    - rich
    - rich-click

tests:
  - script:
      - rapids --help
      - rapids doctor --help

about:
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
