# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: rapids-cli
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install -v .
  python:
    entry_points:
      - driver = rapids_cli.doctor.checks.cuda_driver:check_driver_compatibility
      - gpu = rapids_cli.doctor.checks.gpu:gpu_check
      - gpu_compute_capability = rapids_cli.doctor.checks.gpu:check_gpu_compute_capability
      - cuda = rapids_cli.doctor.checks.cuda_driver:cuda_check
      - driver_compatibility = rapids_cli.doctor.checks.cuda_driver:check_driver_compatibility
      - sdd_nvme = rapids_cli.doctor.checks.sdd_nvme:check_sdd_nvme
      - memory_to_gpu_ratio = rapids_cli.doctor.checks.memory:check_memory_to_gpu_ratio
      - nvlink_status = rapids_cli.doctor.checks.nvlink:check_nvlink_status

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.0
  run:
    - python
    - importlib-metadata >=4.13.0
    - nvidia-ml-py >=12.0
    - packaging
    - psutil
    - rich
    - rich-click

tests:
  - script:
      - rapids --help
      - rapids doctor --help

about:
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
